### ISSUE TITLE
failed to build ccache with download error of xxHash

### ISSUE THREAD

**Issue by poltpolt** [jonaski/mxe-qt#607]
What is strange is that of course I can resolved github.com in my Opensuse Slowroll system.

attaching the log
[ccache_x86_64-pc-linux-gnu.tar.gz](https://github.com/user-attachments/files/18181516/ccache_x86_64-pc-linux-gnu.tar.gz)

**Comment by jonaski** [comment]
network traffic is disabled in MXE build, you need to install the native xxhash for the build to succeed.
